# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/M2DAPIGatekeeper.xcworkspace -scheme M2DAPIGatekeeper -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
